GET http://localhost:3000/memes

###
GET http://localhost:3000/memes/60a295369410a34b48860f69

###
POST http://localhost:3000/memes
Content-Type: application/json

{
    "title": "My second meme",
    "img": "someNewImage.jpg"
}

###
DELETE http://localhost:3000/memes/60a1f2d98e86de098442320d

###
PATCH  http://localhost:3000/memes/60a295369410a34b48860f69
Content-Type: application/json

{
    "title": "My third meme - update",
    "img": "someNewImage.jpg"
}